name: EpicAutomators
description: EpicAutomators
main: com.songoda.epicautomators.EpicAutomators
softdepend: [ HolographicDisplays, Vault, EpicHoppers ]
version: maven-version-number
author: Songoda
api-version: 1.13

commands:
  epicautomators:
    description: View information on this plugin.
    default: true
    aliases: [ ea ]
    usage: /ea
